### ISSUE TITLE
Agregar información en español de la landing page

### ISSUE THREAD

**Issue by carlogilmar** [visualpartnership/waffle#1]
![image](https://user-images.githubusercontent.com/17634377/186490630-ad9c90a0-2991-4283-8ab7-fd98c4dc7439.png)

- Cambiar el nombre, datos personales (actualizar la info de la `config`)
- Agregar descripciones del grupo de estudio

**Comment by AliciaGaona** [comment]
Se cambia información y descripciones.

![image](https://user-images.githubusercontent.com/99162884/187758592-de30587d-087f-4f72-9fe5-b9da80016996.png)
