### ISSUE TITLE
Cambiar la imagen que esta en la landing

### ISSUE THREAD

**Issue by carlogilmar** [visualpartnership/waffle#10]
![image](https://user-images.githubusercontent.com/17634377/186570197-eca22e11-c044-44c8-96ba-05b3ad539f15.png)

**Comment by AliciaGaona** [comment]
Se resuelve con issue #1  

![image](https://user-images.githubusercontent.com/99162884/189421641-6e3f3f68-e527-4055-994b-3a9dea905cc3.png)
