### ISSUE TITLE
Agregar readme del proyecto.

### ISSUE THREAD

**Issue by carlogilmar** [visualpartnership/waffle#5]
Agregar un readme en el repo principal:
- Instrucciones de qué necesitas instalar primero (win2, linux y macos)
- Cómo funciona hugo brevemente
- Cómo instalar los submódulos
- Cómo correr el proyecto para verlo en local
- Cómo agregar un nuevo post y actualizar todos los repos.

**Comment by AliciaGaona** [comment]
![image](https://user-images.githubusercontent.com/99162884/189439360-b7ed619a-b0e1-496c-b63f-434d331353d8.png)

Se agrega readme
