### ISSUE TITLE
Nuevo Post: Qué es Go Hugo y Cómo funciona

### ISSUE THREAD

**Issue by carlogilmar** [visualpartnership/waffle#6]

**Comment by AliciaGaona** [comment]
Se agrega post de Go Hugo.

![image](https://user-images.githubusercontent.com/99162884/187847391-4929ae4d-9800-4ff7-ae3a-d48d2393d41c.png)

Se revisará, ya que en local si funciona:

![image](https://user-images.githubusercontent.com/99162884/187847856-378203a1-c374-4c0d-b5a0-5462cf3b059f.png)

Pero en gitHub pages no:

![image](https://user-images.githubusercontent.com/99162884/187847998-93a5cd14-0c7e-4599-b82b-d5828a39920e.png)

**Comment by AliciaGaona** [comment]
![image](https://user-images.githubusercontent.com/99162884/189001118-277a19d4-c665-43e3-888f-ca6d5cdd66ad.png)

Se corrige quitando el guion bajo en el nombre del archivo del post.
