### ISSUE TITLE
Nuevo Post: Qué es git y cómo comenzar a usarlo

### ISSUE THREAD

**Issue by carlogilmar** [visualpartnership/waffle#7]

**Comment by JossPerezT** [comment]
# SOLUCIÓN DEL FEATURE

## 1. Hacer branch del proyecto 
![image](https://user-images.githubusercontent.com/84040594/188777641-1d6fa514-2a80-4c8f-acdb-f884b0ab8f02.png)

## 2. Entramos a los post y creamos un nuevo archivo markdown para nuestro post "Que es Git" 
![image](https://user-images.githubusercontent.com/84040594/189027536-0adef8a1-2e3f-4c11-8093-41a7e544fb30.png)

##  3. Agregamos la información del post
![image](https://user-images.githubusercontent.com/84040594/189027845-963da710-bfed-4d95-829d-b1cc211c0e15.png)

##  4. Construimos le proyecto y lo subimos en el servidor local 
![image](https://user-images.githubusercontent.com/84040594/189031547-c4e0140a-d21b-4e83-87b6-a2db5626dc0d.png)
![image](https://user-images.githubusercontent.com/84040594/189031603-5832b79b-32cd-48fc-a51e-8fe2dd35a08e.png)

##  5. Hacemos merge en la rama principal. 
![image](https://user-images.githubusercontent.com/84040594/189031472-83955da3-7e66-4e48-9a62-f9e4fc564d52.png)

## 6. Construimos proyecto 
![image](https://user-images.githubusercontent.com/84040594/189032489-4dd6f5a2-d04b-4cb4-b121-8708bf6f1850.png)

##  7. listo, nuestro nuevo post esta en nuestro blog 
![image](https://user-images.githubusercontent.com/84040594/189032523-59ba7d42-c0c6-4e37-95b7-12a9c4ac4044.png)
